/*
 * CEI Labs Natas tab theming (content script).
 *
 * Scope, deliberately: this extension only themes the browser TAB
 * (favicon + title text). Native Chromium window-chrome theming (title
 * bar color, toolbar color, etc.) requires either a full custom
 * Chromium build or a signed theme published through the Chrome Web
 * Store -- neither is practical for a self-hosted range image built
 * from stock Kali/Debian chromium, so it was explicitly ruled out
 * rather than half-built. See operator/kali-novnc/README (this
 * extension's own notes) and the PR description for the full
 * investigation.
 *
 * Level/title list is intentionally duplicated (not imported) from
 * CEI-Labs-Wargames' targets/natas/build/generate_banners.py -- these
 * are two separate repositories with no shared build step between them,
 * so this list must be kept in sync by hand if Natas's level titles
 * ever change there.
 */
(function () {
  "use strict";

  var TITLES = {
    0: "View Source",
    1: "Right-Click Block",
    2: "Directory Traversal (Files)",
    3: "Web Crawlers (Robots.txt)",
    4: "Referer Spoofing",
    5: "Cookie Manipulation",
    6: "Hidden Inclusion Files",
    7: "Local File Inclusion (LFI)",
    8: "Reversing Crypto Schemes",
    9: "Command Injection I",
    10: "Command Injection II (Sanitization Bypass)",
    11: "XOR Encryption Bypass",
    12: "Arbitrary File Upload (Web Shell)",
    13: "File Upload Bypass (Magic Bytes)",
    14: "SQL Injection (SQLi)"
  };

  function levelFromPort(port) {
    var n = parseInt(port, 10) - 8000;
    return (n >= 0 && n <= 14) ? n : null;
  }

  // Same cool(recon)->hot(exploitation) hue sweep as
  // CEI-Labs-Wargames/targets/natas/build/generate_themes.py's
  // _progression_hue() -- kept numerically identical on purpose so the
  // tab favicon's color matches the page background's color direction,
  // even though the two are generated by entirely separate code in
  // separate repos.
  function progressionHue(n) {
    var HUE_START = 200, HUE_END = -20;
    return HUE_START + (HUE_END - HUE_START) * (n / 14);
  }

  // Is the CURRENT page already rendering as "solved"? Reads the
  // cei-solved/cei-locked class that CEI-Labs-Wargames' own
  // cei-natas-banner.php sets server-side on <body> -- deliberately NOT
  // reimplementing solve-state detection here, to avoid two divergent
  // definitions of "solved" across two repos. If that class is absent
  // (e.g. this Natas build predates that change, or natas14 which never
  // reaches solved under that signal), this just falls back to
  // "unknown" and renders the locked/neutral favicon.
  function isSolved() {
    var body = document.body;
    if (!body) return false;
    return body.classList.contains("cei-solved");
  }

  function buildFavicon(level, solved) {
    var size = 32;
    var canvas = document.createElement("canvas");
    canvas.width = size;
    canvas.height = size;
    var ctx = canvas.getContext("2d");

    var hue = progressionHue(level);
    var lightness = solved ? 52 : 34; // solved = brighter/warmer fill
    ctx.fillStyle = "hsl(" + hue.toFixed(1) + "deg 60% " + lightness + "%)";
    ctx.beginPath();
    ctx.arc(size / 2, size / 2, size / 2 - 1, 0, Math.PI * 2);
    ctx.fill();

    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 14px monospace";
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText(String(level), size / 2, size / 2 + 1);

    // Small badge in the corner: a filled dot for solved, a hollow ring
    // for locked -- distinguishable at favicon size without relying on
    // color alone (colorblind-safe, and still legible shrunk to 16px).
    var bx = size - 7, by = size - 7;
    if (solved) {
      ctx.fillStyle = "#f4fff2";
      ctx.beginPath();
      ctx.arc(bx, by, 4, 0, Math.PI * 2);
      ctx.fill();
    } else {
      ctx.strokeStyle = "#00000066";
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.arc(bx, by, 4, 0, Math.PI * 2);
      ctx.stroke();
    }

    return canvas.toDataURL("image/png");
  }

  function applyFavicon(dataUrl) {
    var links = document.querySelectorAll('link[rel~="icon"]');
    for (var i = 0; i < links.length; i++) {
      links[i].parentNode.removeChild(links[i]);
    }
    var link = document.createElement("link");
    link.rel = "icon";
    link.type = "image/png";
    link.href = dataUrl;
    document.head.appendChild(link);
  }

  function applyTitle(level, solved) {
    var title = TITLES.hasOwnProperty(level) ? TITLES[level] : "Unknown Level";
    var prefix = solved ? "[SOLVED] " : "";
    document.title = prefix + "Natas " + level + ": " + title;
  }

  function run() {
    var level = levelFromPort(window.location.port);
    if (level === null) return;
    var solved = isSolved();
    applyTitle(level, solved);
    applyFavicon(buildFavicon(level, solved));
  }

  run();
})();
